apiVersion: v2
name: webui
description: A Helm chart for openQA webui inside Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: postgresql
    version: 6.5.0
    repository: https://charts.helm.sh/stable
    condition: postgresql.enabled
