apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "webui.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: {{ .Values.baseUrl }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "webui.fullname" . }}
              port:
                name: webui
        - path: /api/v1/ws
          pathType: Prefix
          backend:
            service:
              name: {{ include "webui.fullname" . }}
              port:
                name: websockets
        - path: /livehandler
          pathType: Prefix
          backend:
            service:
              name: {{ include "webui.fullname" . }}
              port:
                name: livehandler
