apiVersion: v1
kind: Service
metadata:
  name: {{ include "webui.fullname" . }}
  labels:
    {{- include "webui.labels" . | nindent 4 }}
spec:
  ports:
    - name: webui
      port: 9526
    - name: websockets
      port: 9527
    - name: livehandler
      port: 9528
    - name: scheduler
      port: 9529
  selector:
    {{- include "webui.selectorLabels" . | nindent 4 }}
